# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='value1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='value2',
            field=models.IntegerField(null=True),
        ),
    ]
